interface paths {
  dashboard: string;
  home: string;
  login: string;
  register: string;
  bookingForm: string;
  contactUs: string;
  aCursoryLook: string;
  ourVisionMission: string;
  achievments: string;
  leadership: string;
  formerChairpersons: string;
  formerManagingDirectors: string;
  whoIsWho: string;
  flimEcoSystem: string;
  overview: string;
  objectives: string;
  studiosPastGlory: string;
  boardOfDirectors: string;
  whosWho: string;
  odishaIndiasBestKeptSecret: string;
  echoesofhistory: string;
  climate: string;
  cinematicHeritage: string;
  geographicalFeature: string;
  culturalLegacy: string;
  majorFestivals: string;
  archivesInsight: string;
  keyPriorities: string;
  odiaFilmAnthology: string;
  vaultofPreservedFilms: string;
  archivalGallery: string;
  userDashboard: string;
  bookingHistory: string;
  paymentHistory: string;
  newBooking: string;
  profile: string;
  adminDashboard: string;
  allBookings: string;
  paymentDetails: string;
  calender: string;
  confirmation: string; 
  preview: string;
  talentlist: string;
  locationDirectory: string;
  locationDetails: string;
  filmEcoSystem: string;
  test: string;
  RoleBasedRedirect: string;
  resetPassword: string;
  forgetPassword: string;
  policyGuidelines: string;
  odishaSilverScreen: string;
  publications: string;
  tender: string;
  policy: string;
}

export const paths: paths = {
  dashboard: '/dashboard',
  home: '/',
  aCursoryLook: '/a-cursory-look',
  ourVisionMission: 'our-vision-and-mission',
  achievments: '/achievments',
  leadership: '/leadership',
  formerChairpersons: '/former-chair-persons',
  formerManagingDirectors: '/former-managingdirectors',
  whoIsWho: '/who-is-who',
  flimEcoSystem: '/film-eco-system',
  policyGuidelines: '/policy-guidelines',
  bookingForm: '/booking-form',
  login: '/login',
  register: '/register',
  contactUs: '/contact-us',
  overview: '/overview',
  objectives: '/objectives',
  studiosPastGlory: '/studios-past-glory',
  boardOfDirectors: '/board-of-directors',
  whosWho: '/whos-who',
  odishaIndiasBestKeptSecret: '/odisha-indias-best-kept-secret',
  echoesofhistory: '/echoes-of-history',
  climate: '/climate',
  cinematicHeritage: '/cinematic-heritage',
  geographicalFeature: '/geographical-feature',
  culturalLegacy: '/cultural-legacy',
  majorFestivals: '/major-festivals',
  archivesInsight: '/archives-insight',
  keyPriorities: '/key-priorities',
  odiaFilmAnthology: '/odia-film-anthology',
  vaultofPreservedFilms: '/vault-of-preserved-films',
  archivalGallery: '/archival-gallery',
  userDashboard: '/user-dashboard',
  bookingHistory: '/booking-history',
  paymentHistory: '/payment-history',
  newBooking: '/new-booking',
  profile: '/profile',
  adminDashboard: '/admin-dashboard',
  allBookings: '/all-bookings',
  paymentDetails: '/payment-details',
  calender: '/calender',
  confirmation: '/confirmation',
  preview: '/preview',
  talentlist: '/talent-list',
  locationDirectory: '/location-directory',
  locationDetails: '/location-details',
  filmEcoSystem: '/film-eco-system',
  test: '/test',
  RoleBasedRedirect: '/role-based-redirect',
  forgetPassword: '/forget-password',
  resetPassword: '/reset-password/:token',
  odishaSilverScreen: '/odisha-silver-screen',
  publications: '/publications',
  tender: '/tender',
  policy: '/policy',
};
